---
# Customise these (or not) for your site.
prefers:
    loc:
        - FR
        - global
min_test: 5
max_test: 10
ratio: 0.5

# Runtime config; unlikely to require modification.
sites_age: 86400
sites_url: 'https://raw.githubusercontent.com/falling-sky/source/master/js/sites_parsed_raw.yaml'
sites_file: 'sites.yaml'
